% Print plot of the game
print_introduction :-
    write('Welcome to Baking B(re)ad: The Lab Escape!'),
    nl,
    write('You are Walter Black, a brilliant baker working in Sus\'s lab.'),
    nl,
    write('You are famous for your blue crystal muffins.'),
    nl,
    write('Your partner, known as Jesse Yellowman, is with you.'),
    nl,
    write('He is not as smart as you, but he is loyal and can help you.'),
    nl,
    write('Anytime you are lost, type "help", and Jesse will give you a hint.'),
    nl,
    write('After a botched deal, your situation has become dire.'),
    nl,
    write('You feel like one mistake could be your last.'),
    nl,
    write('After a long day of work it is time to add the last ingredient to your product.'),
    nl,
    write('Good luck!'),
    nl.